aoc/util/objects/Advent_of_Code_Problem__c/Advent_of_Code_Problem__c.object-meta.xml
<CustomObject>
    <label>Advent of Code Problem</label>
    <nameField>
        <label>Problem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advent of Code Problems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aoc/util/objects/Advent_of_Code_Problem__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked when the solutions has finished caculating.</description>
    <label>Completed</label>
    <type>Checkbox</type>
</CustomField>

aoc/util/objects/Advent_of_Code_Problem__c/fields/Completed_Time__c.field-meta.xml
<CustomField>
    <fullName>Completed_Time__c</fullName>
    <label>Completed</label>
    <type>DateTime</type>
</CustomField>

aoc/util/objects/Advent_of_Code_Problem__c/fields/Input__c.field-meta.xml
<CustomField>
    <fullName>Input__c</fullName>
    <description>Input of this Advent of Code Problem</description>
    <label>Input</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

aoc/util/objects/Advent_of_Code_Problem__c/fields/Part_1_Solution__c.field-meta.xml
<CustomField>
    <fullName>Part_1_Solution__c</fullName>
    <description>Solution of Part 1</description>
    <label>Part 1 Solution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

aoc/util/objects/Advent_of_Code_Problem__c/fields/Part_2_Solution__c.field-meta.xml
<CustomField>
    <fullName>Part_2_Solution__c</fullName>
    <description>Solution of Part 2</description>
    <label>Part 2 Solution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

aoc/util/objects/Advent_of_Code_Problem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Field to store the status of a running calculation</description>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

aoc/day04/objects/AoC04_Candidate__c/AoC04_Candidate__c.object-meta.xml
<CustomObject>
    <label>AoC04 Candidate</label>
    <nameField>
        <label>AoC04 Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AoC04 Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aoc/day04/objects/AoC04_Candidate__c/fields/Advent_of_Code_Problem__c.field-meta.xml
<CustomField>
    <fullName>Advent_of_Code_Problem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advent of Code Problem</label>
    <referenceTo>Advent_of_Code_Problem__c</referenceTo>
    <relationshipLabel>AoC04 Candidates</relationshipLabel>
    <relationshipName>AoC04_Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

aoc/day04/objects/AoC04_Candidate__c/fields/Valid_for_part2__c.field-meta.xml
<CustomField>
    <fullName>Valid_for_part2__c</fullName>
    <formula>LEN(Name) - LEN(SUBSTITUTE(Name,&#39;0&#39;,&#39;&#39;)) == 2 ||
LEN(Name) - LEN(SUBSTITUTE(Name,&#39;1&#39;,&#39;&#39;)) == 2 ||
LEN(Name) - LEN(SUBSTITUTE(Name,&#39;2&#39;,&#39;&#39;)) == 2 ||
LEN(Name) - LEN(SUBSTITUTE(Name,&#39;3&#39;,&#39;&#39;)) == 2 ||
LEN(Name) - LEN(SUBSTITUTE(Name,&#39;4&#39;,&#39;&#39;)) == 2 ||
LEN(Name) - LEN(SUBSTITUTE(Name,&#39;5&#39;,&#39;&#39;)) == 2 ||
LEN(Name) - LEN(SUBSTITUTE(Name,&#39;6&#39;,&#39;&#39;)) == 2 ||
LEN(Name) - LEN(SUBSTITUTE(Name,&#39;7&#39;,&#39;&#39;)) == 2 ||
LEN(Name) - LEN(SUBSTITUTE(Name,&#39;8&#39;,&#39;&#39;)) == 2 ||
LEN(Name) - LEN(SUBSTITUTE(Name,&#39;9&#39;,&#39;&#39;)) == 2</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valid_for_part2</label>
    <type>Checkbox</type>
</CustomField>

aoc/day04/classes/AoC4_Batch.cls
/**
 * Created by micro on 30.12.2019.
 */

public with sharing class AoC4_Batch implements Database.Batchable<AoC04_Candidate__c> {

    Id problemId;

    public AoC4_Batch(Id problemId) {
        this.problemId = problemId;
    }

    public void execute(Database.BatchableContext context, List<SObject> objects) {
        // just try insert and ignore
        Database.insert(objects, false);
    }


    public void finish(Database.BatchableContext context) {
        Integer part1 = [SELECT COUNT() FROM AoC04_Candidate__c WHERE Advent_of_Code_Problem__c = :problemId];
        Integer part2 = [SELECT COUNT() FROM AoC04_Candidate__c WHERE Advent_of_Code_Problem__c = :problemId AND Valid_for_part2__c = TRUE];

        Advent_of_Code_Problem__c problem = new Advent_of_Code_Problem__c(
                Id = problemId,
                Part_1_Solution__c = part1 + '',
                Part_2_Solution__c = part2 + '',
                Status__c = 'Completed',
                Completed__c = true,
                Completed_Time__c = Datetime.now()
        );
        update problem;
    }

    public List<AoC04_Candidate__c> start(Database.BatchableContext context) {
        Advent_of_Code_Problem__c problem = [SELECT Id,Input__c FROM Advent_of_Code_Problem__c WHERE Id = :problemId];
        List<String> numbers = problem.Input__c.split('-');
        Integer start = Integer.valueOf(numbers.get(0));
        Integer ending = Integer.valueOf(numbers.get(1));
        List<AoC04_Candidate__c> candidates = new List<AoC04_Candidate__c>();
        for (Integer i = start; i < ending; i++) {
            candidates.add(new AoC04_Candidate__c(Name = i + '', Advent_of_Code_Problem__c = problemId));
        }

        problem.Started__c = Datetime.now();
        problem.Status__c = 'Started';
        update problem;

        return candidates;
    }
}