aoc/util/objects/Advent_of_Code_Problem__c/Advent_of_Code_Problem__c.object-meta.xml
<CustomObject>
    <label>Advent of Code Problem</label>
    <nameField>
        <label>Problem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advent of Code Problems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aoc/util/objects/Advent_of_Code_Problem__c/fields/Input__c.field-meta.xml
<CustomField>
    <fullName>Input__c</fullName>
    <description>Input of this Advent of Code Problem</description>
    <label>Input</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

aoc/util/objects/Advent_of_Code_Problem__c/fields/Part_1_Solution__c.field-meta.xml
<CustomField>
    <fullName>Part_1_Solution__c</fullName>
    <description>Solution of Part 1</description>
    <label>Part 1 Solution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

aoc/util/objects/Advent_of_Code_Problem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Field to store the status of a running calculation</description>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

aoc/day02/objects/AoC02_Part2_Try__e/AoC02_Part2_Try__e.object-meta.xml
<CustomObject>
    <label>AoC02 Part2 Try</label>
    <pluralLabel>AoC02 Part2 Tries</pluralLabel>
</CustomObject>

aoc/day02/objects/AoC02_Part2_Try__e/fields/Noun__c.field-meta.xml
<CustomField>
    <fullName>Noun__c</fullName>
    <label>Noun</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

aoc/day02/objects/AoC02_Part2_Try__e/fields/ProblemId__c.field-meta.xml
<CustomField>
    <fullName>ProblemId__c</fullName>
    <description>Advent_of_Code_Problem we are trying to solve</description>
    <label>ProblemId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

aoc/intcode/objects/Intcode_Processor__c/Intcode_Processor__c.object-meta.xml
<CustomObject>
    <label>Intcode Processor</label>
    <nameField>
        <label>Intcode Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intcode Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aoc/intcode/objects/Intcode_Processor__c/fields/Advent_of_Code_Problem__c.field-meta.xml
<CustomField>
    <fullName>Advent_of_Code_Problem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advent of Code Problem</label>
    <referenceTo>Advent_of_Code_Problem__c</referenceTo>
    <relationshipLabel>Intcode Processors</relationshipLabel>
    <relationshipName>Intcode_Processors</relationshipName>
    <type>Lookup</type>
</CustomField>

aoc/intcode/objects/Intcode_Processor__c/fields/Memory__c.field-meta.xml
<CustomField>
    <fullName>Memory__c</fullName>
    <label>Memory</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

aoc/intcode/objects/Intcode_Processor__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&#39;New&#39;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Stopped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

aoc/day02/classes/AoC02.cls
/**
 * Created by micro on 28.12.2019.
 */

public with sharing class AoC02 {

    public static void solvePart1(Advent_of_Code_Problem__c problem) {

        Intcode_Processor__c p = new Intcode_Processor__c(
                Name = problem.Name + '-Part1',
                Memory__c = setVerbNoun(problem.Input__c, 12,2),
                Status__c = Intcode.STATUS_RUNNING
        );
        insert p;
        p = [SELECT Memory__c FROM Intcode_Processor__c WHERE Id = :p.Id];

        problem.Part_1_Solution__c = Intcode.parseMemory(p.Memory__c).get(0) + '';
    }

    public static void solvePart2(Advent_of_Code_Problem__c problem) {
        List<AoC02_Part2_Try__e> events = new List<AoC02_Part2_Try__e>();
        for (Integer noun = 1; noun < 101; noun++) {
            events.add(new AoC02_Part2_Try__e(
                        ProblemId__c = problem.Id,
                        Noun__c = noun
            ));
        }
        System.debug(events);
        EventBus.publish(events);
    }

    public static Long runInMemory(Advent_of_Code_Problem__c problem, Long noun, Long verb) {
        List<Long> memory = Intcode.parseMemory(problem.Input__c);
        memory.set(1, noun);
        memory.set(2, verb);
        Intcode i = new Intcode(memory);
        i.run();
        return i.memory.get(0);
    }

    private static String setVerbNoun(String memory, Long noun, Long verb) {
        List<Long> longs = Intcode.parseMemory(memory);
        longs.set(1, noun); longs.set(2, verb);
        return String.join(longs, ',');
    }
}