aoc/util/objects/Advent_of_Code_Problem__c/Advent_of_Code_Problem__c.object-meta.xml
<CustomObject>
    <label>Advent of Code Problem</label>
    <nameField>
        <label>Problem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advent of Code Problems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aoc/util/objects/Advent_of_Code_Problem__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <description>Day of this Problem</description>
    <label>Day</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

aoc/util/objects/Advent_of_Code_Problem__c/fields/Input__c.field-meta.xml
<CustomField>
    <fullName>Input__c</fullName>
    <description>Input of this Advent of Code Problem</description>
    <label>Input</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

aoc/util/objects/Advent_of_Code_Problem__c/fields/Part_1_Solution__c.field-meta.xml
<CustomField>
    <fullName>Part_1_Solution__c</fullName>
    <description>Solution of Part 1</description>
    <label>Part 1 Solution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

aoc/util/objects/Advent_of_Code_Problem__c/fields/Part_2_Solution__c.field-meta.xml
<CustomField>
    <fullName>Part_2_Solution__c</fullName>
    <description>Solution of Part 2</description>
    <label>Part 2 Solution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

aoc/day03/classes/AoC03_Test.cls
/**
 * Created by micro on 29.12.2019.
 */

@IsTest
private class AoC03_Test {
/*
Not Testtable because of BigObjects


    @IsTest
    static void testTinyProblem() {
        String input = 'R8,U5,L5,D3\nU7,R6,D4,L4';
        Advent_of_Code_Problem__c problem = solveProblem(input);
        System.assertEquals('6', problem.Part_1_Solution__c);
        System.assertEquals('30', problem.Part_2_Solution__c);
    }

    @IsTest
    static void testSmallProblem() {
        String input = 'R75,D30,R83,U83,L12,D49,R71,U7,L72\nU62,R66,U55,R34,D71,R55,D58,R83';
        Advent_of_Code_Problem__c problem = solveProblem(input);
        System.assertEquals('159', problem.Part_1_Solution__c);
        System.assertEquals('610', problem.Part_2_Solution__c);
    }

    @IsTest
    static void test2Problems() {
        String input1 = 'R75,D30,R83,U83,L12,D49,R71,U7,L72\nU62,R66,U55,R34,D71,R55,D58,R83';
        String input2 = 'R98,U47,R26,D63,R33,U87,L62,D20,R33,U53,R51\nU98,R91,D20,R16,D67,R40,U7,R15,U6,R7';
        Advent_of_Code_Problem__c problem1 = solveProblem(input1);
        Advent_of_Code_Problem__c problem2 = solveProblem(input2);
        System.assertEquals('159', problem1.Part_1_Solution__c);
        System.assertEquals('610', problem1.Part_2_Solution__c);
        System.assertEquals('135', problem2.Part_1_Solution__c);
        System.assertEquals('410', problem2.Part_2_Solution__c);
    }

    @IsTest
    static void testBigStep() {
        String input = 'R1000,U573,L25,U468,L833,D867,R515,D941\nL1004,U110,R738,D383,R606,U840,L123,D756';
        Advent_of_Code_Problem__c problem = solveProblem(input);
    }

    private static Advent_of_Code_Problem__c solveProblem(String input) {
        Advent_of_Code_Problem__c problem = new Advent_of_Code_Problem__c(
                Day__c = '03',
                Input__c = input
        );
        insert problem;

        Test.getEventBus().deliver();
        problem = [SELECT Part_1_Solution__c,Part_2_Solution__c FROM Advent_of_Code_Problem__c WHERE Id = :problem.Id];
        return problem;
    }

 */
}