aoc/util/objects/Advent_of_Code_Problem__c/Advent_of_Code_Problem__c.object-meta.xml
<CustomObject>
    <label>Advent of Code Problem</label>
    <nameField>
        <label>Problem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advent of Code Problems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aoc/util/objects/Advent_of_Code_Problem__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked when the solutions has finished caculating.</description>
    <label>Completed</label>
    <type>Checkbox</type>
</CustomField>

aoc/util/objects/Advent_of_Code_Problem__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <description>Day of this Problem</description>
    <label>Day</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

aoc/util/objects/Advent_of_Code_Problem__c/fields/Input__c.field-meta.xml
<CustomField>
    <fullName>Input__c</fullName>
    <description>Input of this Advent of Code Problem</description>
    <label>Input</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

aoc/util/objects/Advent_of_Code_Problem__c/fields/Part_1_Solution__c.field-meta.xml
<CustomField>
    <fullName>Part_1_Solution__c</fullName>
    <description>Solution of Part 1</description>
    <label>Part 1 Solution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

aoc/util/objects/Advent_of_Code_Problem__c/fields/Part_2_Solution__c.field-meta.xml
<CustomField>
    <fullName>Part_2_Solution__c</fullName>
    <description>Solution of Part 2</description>
    <label>Part 2 Solution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

aoc/day01/classes/AoC01_Test.cls
/**
 * Created by micro on 28.12.2019.
 */

@IsTest
private class AoC01_Test {
    @IsTest
    static void testDay01() {
        Advent_of_Code_Problem__c problem = new Advent_of_Code_Problem__c(
                Day__c = '01',
                Input__c = '100756'
        );
        Test.enableChangeDataCapture();
        insert problem;
        Test.getEventBus().deliver();
        problem = [SELECT Part_1_Solution__c, Part_2_Solution__c,Completed__c FROM Advent_of_Code_Problem__c];
        System.assert(!problem.Completed__c);
        Test.getEventBus().deliver();
        Test.getEventBus().deliver();
        Test.getEventBus().deliver();
        Test.getEventBus().deliver();
        Test.getEventBus().deliver();
        Test.getEventBus().deliver();
        Test.getEventBus().deliver();
        Test.getEventBus().deliver();
        Test.getEventBus().deliver();
        Test.getEventBus().deliver();

        problem = [SELECT Part_1_Solution__c, Part_2_Solution__c,Completed__c FROM Advent_of_Code_Problem__c];
        System.assert(problem.Completed__c);
        System.assertEquals('33583', problem.Part_1_Solution__c);
        System.assertEquals('50346', problem.Part_2_Solution__c);
    }
}