aoc/util/objects/Advent_of_Code_Problem__c/Advent_of_Code_Problem__c.object-meta.xml
<CustomObject>
    <label>Advent of Code Problem</label>
    <nameField>
        <label>Problem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advent of Code Problems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aoc/util/objects/Advent_of_Code_Problem__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <description>Day of this Problem</description>
    <label>Day</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

aoc/util/objects/Advent_of_Code_Problem__c/fields/Input__c.field-meta.xml
<CustomField>
    <fullName>Input__c</fullName>
    <description>Input of this Advent of Code Problem</description>
    <label>Input</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

aoc/util/objects/Advent_of_Code_Problem__c/fields/Part_1_Solution__c.field-meta.xml
<CustomField>
    <fullName>Part_1_Solution__c</fullName>
    <description>Solution of Part 1</description>
    <label>Part 1 Solution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

aoc/util/objects/Advent_of_Code_Problem__c/fields/Part_2_Solution__c.field-meta.xml
<CustomField>
    <fullName>Part_2_Solution__c</fullName>
    <description>Solution of Part 2</description>
    <label>Part 2 Solution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

aoc/day02/classes/AoC02_Test.cls
/**
 * Created by micro on 28.12.2019.
 */

@IsTest
private class AoC02_Test {
    @IsTest
    static void testSolution() {
        String input = '1,0,0,3,1,1,2,3,1,3,4,3,1,5,0,3,2,13,1,19,1,19,10,23,1,23,13,27,1,6,27,31,1,9,31,35,2,10,35,39,1,39,6,43,1,6,43,47,2,13,47,51,1,51,6,55,2,6,55,59,2,59,6,63,2,63,13,67,1,5,67,71,2,9,71,75,1,5,75,79,1,5,79,83,1,83,6,87,1,87,6,91,1,91,5,95,2,10,95,99,1,5,99,103,1,10,103,107,1,107,9,111,2,111,10,115,1,115,9,119,1,13,119,123,1,123,9,127,1,5,127,131,2,13,131,135,1,9,135,139,1,2,139,143,1,13,143,0,99,2,0,14,0';

        Advent_of_Code_Problem__c problem = new Advent_of_Code_Problem__c(
                Name = 'Day 02 Full',
                Day__c = '02',
                Input__c = input
        );
        insert problem;

        problem = [SELECT Id,Part_2_Solution__c,Part_1_Solution__c FROM Advent_of_Code_Problem__c WHERE Id = :problem.Id];
        System.assertEquals(7210630 + '', problem.Part_1_Solution__c);

        //Test is to expensive (CPU Time Limit)
        //Test.getEventBus().deliver();
        //problem = [SELECT Id,Part_2_Solution__c,Part_1_Solution__c FROM Advent_of_Code_Problem__c WHERE Id = :problem.Id];
        //System.assertEquals(3892 + '', problem.Part_2_Solution__c);
    }
}